### ISSUE TITLE
Main vs master

### ISSUE THREAD

**Issue by MarinaPaley** [Kira-Kotova/LabsSQL#1]
_&laquo;Хотелось бы внести ясность...&raquo;_ какая из веток является рабочей, и почему она получила ТАКОЕ название?

Возможно [эта команда](https://stackoverflow.com/a/3631775) поможет разобраться:
```sh
$ git branch -vv
```

Например, у меня это дало такой результат
![image](https://user-images.githubusercontent.com/26978698/107536375-c35eb480-6bd2-11eb-9dc2-7c1461da8be0.png)

То же самое видно и через  Git Extensions:
![image](https://user-images.githubusercontent.com/26978698/107536530-eee19f00-6bd2-11eb-9b4f-dc55f8e2b2c7.png)

Возможно несогласованность между главными ветками на здесь и сейчас &ndash; хорошо, но в дальнейшем вряд ли будет удобным.

**Comment by Kira-Kotova** [comment]
Главная ветка теперь одна - master
